# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core project to Azure Function App - esp32-data

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

    #  - name: 'Resolve Project Dependencies Using Dotnet'
    #    shell: bash
    #    run: |
    #      pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
    #      dotnet build --configuration Release --output ./output
    #      popd

      - name: 'Restore Dependencies for All Projects'
        shell: bash
        run: |
          dotnet restore

      - name: 'Run Unit Tests'
        shell: bash
        run: |
          dotnet test ESP32SensorSystem.SaveToDbTests/ESP32SensorSystem.SaveToDbTests.csproj --no-build --verbosity normal

      - name: 'Build Project'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'esp32-data'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_749BABA4C3CE455F8E6302E3A26B103B }}
